CURRENTLY_LOGGED = "El usuario ya ha iniciado sesión"
FORBIDDEN = "El usuario no puede hacer esta acción"
LOGGED = "Sesión iniciada"
LOGGED_OUT = "Sesión cerrada"
NOT_LOGGED = "Usuario no ha iniciado sesión"
